version: '3.8'

services:
  preqin-technical-test:
    container_name: preqin-technical-test
    build:
      context: .
    volumes:
      - '/app/node_modules'
    ports:
      - 80:80
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true